name: autofix.ci
on:
  pull_request:
    branches: [main]
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          yarn
          yarn prettier . --write
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"